webhooks:
  urls:
    - https://webhooks.gitter.im/e/3069b7e759e1d02548c1
  on_success: always  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
language: node_js
node_js:
  - 'node'
