webhooks:
  urls:
    - https://webhooks.gitter.im/e/0fe0629b79405afc6e48
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
language: node_js
node_js:
  - 'node'
