version: '3'
services:
  web:
    container_name: brf-energi-web
    build:
      context: .
      args:
        - NODE_ENV
    env_file: .env
    ports:
      - '${PORT}:${PORT}'

  mongo:
    container_name: brf-energi-mongo
    image: 'mongo:5.0.6'
