version: '3'
services:
  web:
    restart: always
    container_name: brf-energi-web
    depends_on:
      - mongo
    build:
      context: .
      args:
        - NODE_ENV
    env_file: .env
    ports:
      - '${PORT}:${PORT}'

  mongo:
    restart: always
    container_name: brf-energi-mongo
    image: 'mongo:5.0.6'
